### ISSUE TITLE
[1.18] REQUEST: Pickup enchantment desc added to mods for another mod

### ISSUE THREAD

**Issue by kwpugh** [shaksternano/WMITAF#1]
Many mods, mine included, have added descriptions for our enchantments for another popular godlike yours, which is not quite the same and is not available for 1.18.

Is it possible for you to pickup the descriptions and add them to the tooltips?

Example of lang file description, if you were not already aware of them.

![Screen Shot 2021-11-21 at 2 03 15 PM](https://user-images.githubusercontent.com/8809210/142777184-a2b31d05-326e-47a1-bacb-55117dddf1ad.png)

Thanks for considering.

**Comment by shaksternano** [comment]
I'll wait until a bit after 1.18 releases before looking into this in case the enchantment descriptions mod releases an update for 1.18.

**Comment by shaksternano** [comment]
Enchantment descriptions does actually work on 1.18 if you remove the version check, so there's no need for me to do this.
