### ISSUE TITLE
Can not fully uninstall the mod

### ISSUE THREAD

**Issue by Eatham532** [shaksternano/WMITAF#5]
I removed the mod from my mods folder and the tooltips still show.

**Comment by shaksternano** [comment]
This mod doesn't add tooltips, it just modifies them

**Comment by Eatham532** [comment]
Well I think the modified tooltips have stayed.

**Comment by shaksternano** [comment]
I think there's another mod that does the same thing as this one, don't know what it's called though.

**Comment by Eatham532** [comment]
That is what I am trying to find out. I had EMI installed that did the same thing. But I disabled that feature.

**Comment by shaksternano** [comment]
Closing as this is unrelated to this mod
